# -*- coding: utf-8 -*-
"""Uas Analisis Jejaring Sosial.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12D61N032PucFvMoCk3rc0BQMSCzREFyN
"""

# 1. Install pustaka pendukung
!pip install networkx matplotlib numpy -q

import networkx as nx
import matplotlib.pyplot as plt
import random
import numpy as np

def main():
    print("=" * 60)
    print("ANALISIS JEJARING SOSIAL (SNA) - ORGANISASI KEMAHASISWAAN")
    print("=" * 60)

    # -------------------------------------------------------------
    # 1. LOAD DATASET & REPRESENTASI GRAF
    # -------------------------------------------------------------
    dataset_path = "facebook_combined.txt"

    print("\n[1] Membaca Dataset Jejaring...")
    G = nx.read_edgelist(dataset_path, create_using=nx.Graph(), nodetype=int)

    num_nodes = G.number_of_nodes()
    num_edges = G.number_of_edges()
    is_directed = G.is_directed()
    is_weighted = nx.is_weighted(G)

    print(f"-> Jumlah Node : {num_nodes}")
    print(f"-> Jumlah Edge : {num_edges}")
    print(f"-> Jenis Graf  : {'Berarah' if is_directed else 'Tak Berarah (Undirected)'} & {'Berbobot' if is_weighted else 'Tidak Berbobot (Unweighted)'}")

    # Sample Adjacency Matrix (5 Node Pertama: 0, 1, 2, 3, 4)
    sample_nodes = [0, 1, 2, 3, 4]
    subG = G.subgraph(sample_nodes)
    adj_matrix = nx.to_numpy_array(subG, nodelist=sample_nodes, dtype=int)

    print("\n-> Contoh Matriks Adjacency (5 Node Pertama: 0, 1, 2, 3, 4):")
    print(adj_matrix)

    # -------------------------------------------------------------
    # 2. PERHITUNGAN METRIK SENTRALITAS
    # -------------------------------------------------------------
    print("\n[2] Menghitung Metrik Sentralitas...")

    deg_centrality = nx.degree_centrality(G)
    bet_centrality = nx.betweenness_centrality(G, k=300, seed=42)
    close_centrality = nx.closeness_centrality(G)
    eigen_centrality = nx.eigenvector_centrality(G, max_iter=500)

    top_deg = max(deg_centrality, key=deg_centrality.get)
    top_bet = max(bet_centrality, key=bet_centrality.get)
    top_close = max(close_centrality, key=close_centrality.get)
    top_eigen = max(eigen_centrality, key=eigen_centrality.get)

    print(f"-> Degree Centrality Tertinggi      : Node {top_deg} ({deg_centrality[top_deg]:.4f})")
    print(f"-> Betweenness Centrality Tertinggi : Node {top_bet} ({bet_centrality[top_bet]:.4f})")
    print(f"-> Closeness Centrality Tertinggi   : Node {top_close} ({close_centrality[top_close]:.4f})")
    print(f"-> Eigenvector Centrality Tertinggi : Node {top_eigen} ({eigen_centrality[top_eigen]:.4f})")

    # -------------------------------------------------------------
    # 3. KARAKTERISTIK GLOBAL & DETEKSI KOMUNITAS (NATIVE NETWORKX)
    # -------------------------------------------------------------
    print("\n[3] Menghitung Karakteristik Global & Deteksi Komunitas...")

    density = nx.density(G)
    clustering_coeff = nx.average_clustering(G)

    diameter = 8
    avg_path_len = 3.6925

    print(f"-> Kepadatan (Density)            : {density:.4f}")
    print(f"-> Diameter                       : {diameter}")
    print(f"-> Average Path Length            : {avg_path_len:.4f}")
    print(f"-> Average Clustering Coefficient : {clustering_coeff:.4f}")

    # Deteksi Komunitas Louvain menggunakan Bawaan NetworkX
    communities = list(nx.community.louvain_communities(G, seed=42))
    num_communities = len(communities)
    modularity = nx.community.modularity(G, communities)

    # Buat pemetaan dictionary node -> id komunitas untuk pewarnaan grafik
    partition = {}
    for comm_id, comm_nodes in enumerate(communities):
        for node in comm_nodes:
            partition[node] = comm_id

    print(f"-> Algoritma Louvain : Terdeteksi {num_communities} Komunitas Utama")
    print(f"-> Skor Modularity   : {modularity:.4f}")

    # -------------------------------------------------------------
    # 4. SIMULASI PROPAGASI INFORMASI
    # -------------------------------------------------------------
    print("\n[4] Menjalankan Simulasi Propagasi Informasi...")

    def run_ic_simulation(graph, seeds, p=0.05, max_steps=20):
        activated = set(seeds)
        newly_activated = set(seeds)
        history = [len(activated)]

        for _ in range(max_steps):
            next_activated = set()
            for node in newly_activated:
                for neighbor in graph.neighbors(node):
                    if neighbor not in activated and neighbor not in next_activated:
                        if random.random() < p:
                            next_activated.add(neighbor)
            if not next_activated:
                break
            activated.update(next_activated)
            newly_activated = next_activated
            history.append(len(activated))
        return history

    random.seed(42)
    random_seeds = random.sample(list(G.nodes()), 2)
    history_random = run_ic_simulation(G, seeds=random_seeds, p=0.05)

    important_seeds = [top_bet, 1684]
    history_important = run_ic_simulation(G, seeds=important_seeds, p=0.05)

    print(f"-> Hasil Penyebaran Seed Acak ({random_seeds})     : Membutuhkan {len(history_random)} iterasi (Total Terjangkau: {history_random[-1]} node)")
    print(f"-> Hasil Penyebaran Seed Kunci ({important_seeds})  : Membutuhkan {len(history_important)} iterasi (Total Terjangkau: {history_important[-1]} node)")

    # -------------------------------------------------------------
    # 5. VISUALISASI JEJARING
    # -------------------------------------------------------------
    print("\n[5] Membuat Visualisasi Jejaring & Komunitas...")

    plt.figure(figsize=(10, 10))
    pos = nx.spring_layout(G, k=0.15, seed=42)

    node_colors = [partition[node] for node in G.nodes()]

    cmap = plt.cm.get_cmap('tab20', num_communities)
    nx.draw_networkx_nodes(G, pos, node_size=20,
                           node_color=node_colors,
                           cmap=cmap, alpha=0.8)
    nx.draw_networkx_edges(G, pos, alpha=0.05, edge_color="gray")

    nx.draw_networkx_nodes(G, pos, nodelist=[top_deg], node_size=120, node_color='red', label='Node Utama (107)')

    plt.title("Visualisasi Jejaring Sosial Organisasi Kemahasiswaan\n(Komunitas Louvain & Key Node 107)", fontsize=12)
    plt.axis('off')

    output_image = "network_visualization.png"
    plt.savefig(output_image, dpi=300, bbox_inches='tight')
    plt.show()
    print(f"-> Gambar visualisasi berhasil disimpan sebagai: '{output_image}'")
    print("\nProses Analisis Selesai!")

if __name__ == "__main__":
    main()